"""Emit the two synthetic tables of the journal draft (tab:sched, tab:kabl)
as complete LaTeX table environments from results/schedule_check.json and
results/k_ablation_synth.json, so that paper/aor/aor.tex can \\input the
file and the inline numbers cannot drift from the result files.

Usage: python3 src/make_appendix_tables.py > paper/aor/tab_synth.tex
"""
import json
from pathlib import Path
R = Path(__file__).resolve().parents[1] / 'results'
NAMES = {'hard-d1000-eps1e-5': r'hard margin, $d{=}1000$, $\varepsilon{=}10^{-5}$',
         'soft-d100-C1': r'$L_2$ overlap, $d{=}100$, $C{=}1$',
         'soft-d1000-C1': r'$L_2$ overlap, $d{=}1000$, $C{=}1$'}
def st(r): return '' if r['status'] == 'converged' else r' (\emph{%s})' % r['status']

sched = json.load(open(R / 'schedule_check.json'))
out = [r"% generated by src/make_appendix_tables.py from results/schedule_check.json and results/k_ablation_synth.json; do not edit",
       r"\begin{table}[htbp]\centering\scriptsize",
       r"\caption{Two-sided schedules on the synthetic instances of Section~\ref{sec:exp} ($n{=}5{,}000$ per class, $k{=}16$, $\varepsilon=10^{-3}$ for the $L_2$ rows, one process at a time, single instances): the unconditional $V$-then-$W$ order versus the schedule of Lemma~\ref{lem:twosided} (larger-gap side first, second side skipped after a drop), an ablation of the skip. Drop steps and skipped second-side steps are counted over the run.}\label{tab:sched}",
       r"\begin{tabular}{lllrrrr}\toprule",
       r"instance & schedule & time (s) & iterations & drops & skips & distance \\\midrule"]
for tag in NAMES:
    for r in [r for r in sched if r['tag'] == tag]:
        lab = 'Lemma~\\ref{lem:twosided}' if r['drop_skip'] else 'unconditional'
        out.append(f"{NAMES[tag]} & {lab} & {r['time']:.1f} & {r['iters']:,} & {r['n_drops']} & {r['n_drop_skips']} & {r['dist']:.6f}{st(r)} \\\\")
    out.append(r"\midrule")
out[-1] = r"\bottomrule"; out += [r"\end{tabular}\end{table}", ""]

kab = json.load(open(R / 'k_ablation_synth.json'))
out += [r"\begin{table}[htbp]\centering\scriptsize",
        r"\caption{Block-size ablation on the same instances (same settings): single MDM ($k{=}1$) versus blocks of $k$ transfers. Iterations fall with $k$; wall-clock does not fall in proportion, because each block iteration touches more columns.}\label{tab:kabl}",
        r"\begin{tabular}{lrrrrr}\toprule",
        r"instance & $k$ & time (s) & iterations & columns & drops \\\midrule"]
for tag in NAMES:
    for r in [r for r in kab if r['tag'] == tag]:
        out.append(f"{NAMES[tag]} & {r['k']} & {r['time']:.1f} & {r['iters']:,}{st(r)} & {r['oracle']:,} & {r['n_drops']} \\\\")
    out.append(r"\midrule")
out[-1] = r"\bottomrule"; out += [r"\end{tabular}\end{table}"]
print("\n".join(out))
