"""Table of the TA I (intersection test) records of the regime battery:
per dataset, verdict, iterations, time and final ||p - q|| with the
tolerance, from results/regime_battery.json (cell FEAS).

Usage: python3 src/ta1_table.py > paper/aor/tab_ta1.tex
"""
import json
import numpy as np
from scipy import stats
rows = json.load(open('results/regime_battery.json'))
def ci(xs):
    xs = np.asarray(xs, float)
    return xs.mean(), (stats.t.ppf(0.975, len(xs) - 1) * xs.std(ddof=1) / np.sqrt(len(xs)) if len(xs) > 1 else 0.0)
out = [r"% generated by src/ta1_table.py from results/regime_battery.json; do not edit",
       r"\begin{table}[htbp]\centering\scriptsize",
       r"\caption{TA~I on the five datasets (linear kernel, full training sets, five seeds, absolute tolerance $10^{-3}$ on $\norm{p-q}$): ``separated'' returns a witness pair with a positive certified lower bound; ``intersect'' returns an iterate with $\norm{p-q}\le10^{-3}$, an $\varepsilon$-witness that the hulls are within $10^{-3}$ of touching, not a proof of intersection. Iterations and the final $\norm{p-q}$ are seed-0 values (covtype: mean over its five splits).}\label{tab:ta1}",
       r"\begin{tabular}{llrrr}\toprule",
       r"dataset & verdict & iterations & time (s) & final $\norm{p-q}$ \\\midrule"]
for ds in ('gisette', 'a9a', 'w8a', 'ijcnn1', 'covtype'):
    sel = [r for r in rows if r['cell'] == 'FEAS' and r['dataset'] == ds]
    m, h = ci([r['time'] for r in sel])
    its = np.mean([r['iters'] for r in sel]); dist = np.mean([r['dist'] for r in sel])
    verdict = {'separated': 'separated', 'intersect': r'intersect ($\varepsilon$-witness)'}[sel[0]['status']]
    dstr = f"{dist:.2f}" if dist > 0.01 else f"{dist:.1e}".replace('e-0', r'\times10^{-').replace('e-', r'\times10^{-') + '}'
    dstr = '$' + dstr + '$'
    out.append(f"{ds} & {verdict} & {its:,.0f} & ${m:.1f}\\pm{h:.1f}$ & {dstr} \\\\")
out += [r"\bottomrule", r"\end{tabular}\end{table}"]
print("\n".join(out))
